approvedGitRepositories:
  - "**"

enableScripts: true
enableGlobalCache: false

nodeLinker: pnp

npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  atlaskit:
    npmRegistryServer: "https://registry.npmjs.org"
npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
