definitions:
  caches:
    yarn: .yarn/cache
  steps:
    - step: &lint_and_unit_tests
        name: Lint and unit tests
        image: node:24-bookworm@sha256:6dac556d980b7f0e5498d08f08cee0ca67798b4ad6c23964a9214920e67758d0
        caches:
          - yarn
        script:
          - corepack enable
          - YARN_ENABLE_HARDENED_MODE=0 yarn install --immutable
          - yarn lint
          - yarn test

    - step: &end_to_end_tests
        name: End-to-end tests
        image: mcr.microsoft.com/playwright:v1.63.0-noble@sha256:eff16c30e6f3f4af0a03fa4b706120d5e9b0891c344a27d64559aff5900a4a27
        clone:
          lfs: true
        caches:
          - yarn
        script:
          - corepack enable
          - YARN_ENABLE_HARDENED_MODE=0 yarn install --immutable
          - HOME=/root yarn playwright test
        artifacts:
          upload:
            - name: Playwright report
              type: scoped
              capture-on: failed
              paths:
                - playwright-report/**

pipelines:
  default:
    - parallel:
      - step: *end_to_end_tests
      - step: *lint_and_unit_tests
