definitions:
  caches:
    yarn: .yarn/cache
  steps:
    - step: &lint_and_unit_tests
        name: Lint and unit tests
        image: node:24-bookworm
        caches:
          - yarn
        script:
          - corepack enable
          - YARN_ENABLE_HARDENED_MODE=0 yarn install --immutable
          - yarn lint
          - yarn test

    - step: &end_to_end_tests
        name: End-to-end tests
        image: mcr.microsoft.com/playwright:v1.62.1-noble@sha256:dcc5531e97840b9b5e794f2814476b21571c5124a3fca2267d73041f56e7580e
        clone:
          lfs: true
        caches:
          - yarn
        script:
          - corepack enable
          - YARN_ENABLE_HARDENED_MODE=0 yarn install --immutable
          - HOME=/root yarn playwright test
        artifacts:
          upload:
            - name: Playwright report
              type: scoped
              capture-on: failed
              paths:
                - playwright-report/**

pipelines:
  default:
    - parallel:
      - step: *end_to_end_tests
      - step: *lint_and_unit_tests
